### ISSUE TITLE
오류 페이지 PNG, 그외 SVG 추가 및 Dropdown box-shadow 수정

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-design-system#21]
### 🔨 Describe

* 에러 바운더리 및 라우터 에러 엘레멘트에 활용될 오류 페이지 PNG를 추가합니다.
* 개발 과정에서 미쳐 추가하지 못한 SVG를 추가합니다.
* 디자인 가이드에 따른 Dropdown box-shadow를 수정합니다.

### ✅ Tasks

- [x] 에러 바운더리 및 라우터 에러 엘레멘트에 활용될 오류 페이지 PNG 추가
- [x] 개발 과정에서 미쳐 추가하지 못한 SVG 추가
- [x] 디자인 가이드에 따른 Dropdown box-shadow를 수정
