### ISSUE TITLE
불필요한 Global CSS, Reset CSS 검토 및 Text 컴포넌트 wordBreak 속성 추가

### ISSUE THREAD

**Issue by semnil5202** [ConceptBe/conceptbe-design-system#25]
### 🔨 Describe

불필요한 Global CSS, Reset CSS 검토 및 Text 컴포넌트 wordBreak 속성 추가

### ✅ Tasks

- [x] Global CSS 불필요한 속성 검토
- [x] Reset CSS 불필요한 속성 검토
- [x] Text 컴포넌트 WordBreak 속성 추가
